version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - app-tier
  
  phpmyadmin:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app-tier
